name: install-3scale-toolbox
description: This is an action that install 3scale toolbox to update and API
author: Felix Roberge
inputs:
  threeScale-token: 
    description: 'The 3 scale token use to connect'
    required: true
  threeScale-url: 
    description: 'The 3 scale url'
    required: true
  api-file:
    description: 'The API you need to upload'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.threeScale-token }}
    - ${{ inputs.threeScale-url }}
    - ${{ inputs.api-file }}