name: install-3scale-toolbox
description: This is an action that install 3scale toolbox to update and API
author: Felix Roberge
branding:
  icon: 'thumbs-up'
  color: 'white'
runs:
  using: 'docker'
  image: 'Dockerfile'